### ISSUE TITLE
Insert image not working

### ISSUE THREAD

**Issue by ishaand** [SohanChy/Lipi#1]
Nothing happens on clicking it.

**Comment by SohanChy** [comment]
This is an incomplete feature.
I haven't worked on this project for some time.
I have plans to do it soon but no eta yet.
If you have found any other problems please let me know. 
Thanks for using my app.

**Comment by ishaand** [comment]
Is that so? Please find time to do it soon.
With this feature, you'll have all the basics covered.
Thank you very much Sohan and others.
I shall notify you if I find any other problems.

**Comment by SohanChy** [comment]
I am the only developer on this project, There is no other developer.
Thank YOU for opening this issue and finally making me get off my ass and fix this.
I've added the image insert feature and also added a minor new option.
The source is already pushed, Release is being uploaded right now.
Please test and let me know :)
