### ISSUE TITLE
Support for YML config files

### ISSUE THREAD

**Issue by ergonlogic** [SohanChy/Lipi#11]
I prefer to use YAML as a Hugo config format, but Lipi appears to assume TOML:

> java.nio.file.NoSuchFileException: /Users/ergonlogic/code/www.aegirproject.org/config.toml[...]

**Comment by SohanChy** [comment]
As mentioned on the [homepage](http://sohanchy.com/Lipi/), Lipi only supports TOML config files at the moment, and since there are some technical hurdles due to the complexity involved in parsing YAML,  there are no plans to support that format any soon. Sorry :(
