### ISSUE TITLE
TOML key case

### ISSUE THREAD

**Issue by guyou** [SohanChy/Lipi#4]
In order to load my config.toml, I had to change Lipi code to convert TOML keys to lowercase (at least for `title`, `baseURL`...)

What is the expected case for TOML configuration? Reading Hugo documentation, it seems to expect lower case.

Is the TOML case insensitive?

**Comment by SohanChy** [comment]
I have totally forgotten this.
But
https://gohugo.io/getting-started/configuration/
Seems to have keys in lower key case for toml.
So for now we should assume that TOML is case sensitive.
I will look into this further.

If you have fixed the code please open another PR :)

**Comment by SohanChy** [comment]
Merged and fixed thanks to @guyou
