### ISSUE TITLE
doesn't work with jre 8 on debian buster

### ISSUE THREAD

**Issue by jmcclelland** [SohanChy/Lipi#7]
I was able to launch lipi after downloading JRE8 from oracle, but when trying to run with jre 8 as shipped by debian, I get:

    0 jamie@turkey:lipi$ ./Lipi\ 0.6.0b.jar 
    Error: Could not find or load main class Lipi
    1 jamie@turkey:lipi$ 

And ideas on what I could do to make this work?

Thanks for writing the software!

**Comment by SohanChy** [comment]
I guess javafx is not included with the JRE by debian.
You have to install in separately.
Please look into this https://stackoverflow.com/questions/34243982/why-is-javafx-is-not-included-in-openjdk-8-on-ubuntu-wily-15-10
